export { colaboradorSidebar } from './colaborador'
export { pesquisaSidebar } from './pesquisa'
export { pesquisaInformativaSidebar } from './pesquisa-informativa'
export { pontoDeVendaSidebar } from './ponto-de-venda'
export { produtoSidebar } from './produto'
export { roteiroSidebar } from './roteiro'
